### ISSUE TITLE
Error when importing from current module

### ISSUE THREAD

**Issue by nameer** [zopefoundation/importchecker#4]
```from . import something``` is not working.

```
Traceback (most recent call last):
  File "/home/nameer/.local/share/virtualenvs/project-d8j3dh2J/bin/importchecker", line 8, in <module>
    sys.exit(main())
  File "/home/nameer/.local/share/virtualenvs/project-d8j3dh2J/lib/python3.6/site-packages/importchecker/importchecker.py", line 301, in main
    db.findModules()
  File "/home/nameer/.local/share/virtualenvs/project-d8j3dh2J/lib/python3.6/site-packages/importchecker/importchecker.py", line 228, in findModules
    self.addModule(module)
  File "/home/nameer/.local/share/virtualenvs/project-d8j3dh2J/lib/python3.6/site-packages/importchecker/importchecker.py", line 246, in addModule
    path = self.resolveDottedModuleName(from_module_name, module)
  File "/home/nameer/.local/share/virtualenvs/project-d8j3dh2J/lib/python3.6/site-packages/importchecker/importchecker.py", line 201, in resolveDottedModuleName                          
    dotted_path = dotted_name.replace('.', '/')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by jugmac00** [comment]
Thank you for reporting this bug.

I can confirm it when 
- creating a test.py with following content
`from . import something`
- installing importchecker
- executing `importchecker test.py`

@nameer I do not know when someone has time to have a look into this issue.

Meanwhile there are many linters out there which can check for unused import statements, e.g. pyflakes
https://pypi.org/project/pyflakes/
